### ISSUE TITLE
Create plan for Hive Global Meet-Up at DML

### ISSUE THREAD

**Issue by ldecoursy** [MozillaHive/HiveGlobal#18]
RACI
- Decision-Maker:
- Driver:
- Consulted:
- Informed: 

We need to confirm budget, owners and next steps for planning the Hive Global Meet-up at DML on June 10.

Here are notes from previous team etherpad:
Proposed pre-DML convening: 
- Mid- to late-afternoon, 2-4 hours, Wed, June 10, 2015
- Cross-Hive Global Meetup a la MozFest 2014
- 50-100ish people
- Room reserved for us at Sheraton (at no cost!) awsm >>we are also known for throwing the best cocktail party so may want to keep that going

Ideas about focuses for Hive Global Meetup?
- Action incubator preview for MozFest 2015
- Facilitated networking (themed, programmatic)
- How to start a Hive? Do we think this would be useful for folks considering Hive - was def a catalyst at MozFest for getting new cities on board - perhaps Simona can invite some US folks she's chatting with+1- we have a team currently in the conversation in L.A which would be awesome to attend yes!
- Cross city connections and networking via similar ideas/interests (thinking Moveable Game jam model and how it is easy to use across different places)
- The on-boarding process: interest form, monthly reports, time line, resources i.e Hive Cookbook, your first community meet up

cc @simonaramkisson @chrislarry33 @mcdermott415 @leahatplay @smithisgeneric @samueledyson

**Comment by chrislarry33** [comment]
We need a DARCI/RACI for this. Sam what level of involvement did you want to have?

**Comment by ldecoursy** [comment]
Latest plan is here: https://docs.google.com/document/d/1UlTkQK1iti-8yME290_fR0ggWaHg11233jRBjah92Ew/edit# Chris to share with ops. 

RACI
- Decision-Maker: CLAW
- Driver: For plan Sam/Simona (execution if a go tbd)
- Consulted: Sam, Meghan (for some framing around theme)
- Informed: MOFO Ops, Learning network team, Paul

**Comment by ldecoursy** [comment]
I owe a few talking points to the team for DML Cafe, then will close this ticket.

**Comment by ldecoursy** [comment]
Old ticket - closing now.
